Metrics:
  Enabled: false

Naming/MethodParameterName:
  Enabled: false

Lint:
  AutoCorrect: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/NumericPredicate:
  Enabled: false

Style/ZeroLengthPredicate:
  Enabled: false
